### ISSUE TITLE
backup/restore state tracking

### ISSUE THREAD

**Issue by JamesClonk** [swisscom/backman#1]
Add internal state to backman. Should be in-memory only, no external database needed.
backman is deployed in a single instance configuration and needs no persistent data. If the app gets restarted/restaged it would abort and lose any ongoing backup/restore operation anyway.

- [x] Add tracking of backup/restore state & progress internally
- [x] Expose new API endpoints to query for ongoing operations, similar to OSBAPI `last_operation`
- [x] Use state API to overhaul `service.html` UI with JS (likely Vue.js)
  - [x] Dynamically load `Backups` list, instead of server-side rendering html
  - [x] Show progressbar or card with spinner upon triggering a backup/restore
  - [x] Continuously poll state / `last_operation`
  - [x] Reload `Backups` upon action completion (backup,restore,delete)
